---
- block:
    - assert: 
        that: "{{ helper.networkifacename is defined }}"
    - set_fact: 
        networkifacename: "{{ helper.networkifacename }}"
  rescue:
    - set_fact:
        networkifacename: "{{ ansible_default_ipv4.interface }}"

- block:
  - set_fact:
      packages:
        - bind
        - bind-utils
        - firewalld
        - vim
        - bash-completion
        - libselinux-python
  
  - set_fact:
      dhcppkgs:
        - dhcp
        - tftp-server

  - set_fact:
      syslinuxpkgs:
        - syslinux
  
  - set_fact:
      owner: nfsnobody
      group: nfsnobody
  
  - set_fact:
      services:
        - named
  when: ansible_distribution_major_version == "7"

- block:
  - set_fact:
      packages:
        - bind
        - bind-utils
        - firewalld
        - vim
        - bash-completion
        - python3-libselinux
  
  - set_fact:
      dhcppkgs:
        - dhcp-server
        - tftp-server

  - set_fact:
      syslinuxpkgs:
        - syslinux

  - set_fact:
      registry:
        - podman
        - httpd-tools
        - jq

  - set_fact:
      registry_services:
        - named
        - firewalld
        - local-registry

  # See Fedora Wiki for changes:
  # https://fedoraproject.org/wiki/Changes/RenameNobodyUser
  - set_fact:
      owner: nobody
      group: nobody
  
  - set_fact:
      services:
        - named
  when: ansible_distribution_major_version == "8"
